### ISSUE TITLE
Including one of the rmf spectral files in the ROOT repository

### ISSUE THREAD

**Issue by cosimoNigro** [open-gamma-ray-astro/joint-crab#7]
Hello @all,

I submitted a PR improving [ROOT](https://github.com/root-project/root) interface with `FITS` data:
https://github.com/root-project/root/pull/5099
It was not possible to read `FITS` tables whose column contained variable-length arrays, such as those in our `rmf` spectral (`OGIP`) files.

I also added a script in the `ROOT` tutorials illustrating this new functionality. 
Since I needed a file to run the tutorial with, I used  the [rmf file from the run 5029747 of MAGIC](https://github.com/open-gamma-ray-astro/joint-crab/blob/master/results/spectra/magic/rmf_obs5029747.fits).

Would it be a problem to include a copy of this file in the official ROOT repository? 
I think including this single specific file does not conflict with the data policy of the paper, also I properly acknowledged in the tutorial macro its provenance:

```C++
/// \file
/// \ingroup tutorial_FITS
/// \notebook
///
/// Open a FITS file with columns containing variable-length arrays. 
/// 
/// ABOUT THE DATA: To illustrate such a case we use a Redistribution 
/// Matrix File (RMF) conform with the HEASARC OGIP specifications
/// OGIP definition
/// https://heasarc.gsfc.nasa.gov/docs/heasarc/ofwg/docs/spectra/ogip_92_007/ogip_92_007.html
/// RMF defintion
/// https://heasarc.gsfc.nasa.gov/docs/heasarc/caldb/docs/memos/cal_gen_92_002/cal_gen_92_002.html#tth_sEc3.1
///
/// Variable-length arrays are used to return the non-null row elements of a 
/// sparse matrix representing the PDF of an energy estimator. 
///
/// Such a format is a standard in spectral data for X-ray astronomy instruments
/// and recently has been adopted by gamma-ray astronomy instruments.
/// The file we use indeed represents the migration matrix of the MAGIC 
/// gamma-ray telescope and is taken from the publicly available data of the 
/// following publication 
/// https://ui.adsabs.harvard.edu/abs/2019A%26A...625A..10N/abstract
/// The file, included here as an example, is available in the github repository
/// associated with the publication
/// https://github.com/open-gamma-ray-astro/joint-crab
/// under this path 
/// https://github.com/open-gamma-ray-astro/joint-crab/blob/master/results/spectra/magic/rmf_obs5029747.fits
/// 
/// \macro_code
/// \macro_output
///
/// \author Cosimo Nigro
```

I wanted to consult the other authors in case somebody had some concern about, or opinion against, the inclusion of the file.

Cosimo

**Comment by cdeil** [comment]
@cosimoNigro - Suggest to go ahead and close this issue.

Anything is fine with me as co-author, but I don't think it's relevant what I or other co-author think. Rather you possibly have to clarify within MAGIC, since what you put [here](https://github.com/open-gamma-ray-astro/joint-crab/tree/master/data/magic#license) sounds like it's not intended purpose of the release at the time from the MAGIC side. Probably the "It is not allowed to use the data outside of this scope (i.e. reproduce paper results) ... " part simply wasn't a good choice, but not the intended sentiment from the MAGIC side, and they'd be OK with other technical use as you propose here.

Wouldn't it be better to use an X-ray example test file?
The Sherpa package uses these test files: https://github.com/sherpa/sherpa-test-data
with example Chandra data - all NASA mission data has no license or any restrictions, and likely their data files are more mature & standard than our gamma-ray efforts?

**Comment by cosimoNigro** [comment]
Hi @cdeil,

many thanks for your suggestion
> all NASA mission data has no license or any restrictions

I did not know this and I tried to search for examples of ref files online but was not successful.
I'll include one of the ref test files from sherpa then since they have no restriction.

Thanks again.
